server.port=7777

spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=coolsoon/kanana-1.5-8b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.num-ctx=16384
spring.ai.ollama.chat.options.num-predict=1024
spring.ai.ollama.chat.options.keep-alive=30m
